---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopmicro-ingress
  namespace: shopmicro
  annotations:
    # Tells NGINX to use Regular Expressions for path matching
    nginx.ingress.kubernetes.io/use-regex: "true"
    # Captures everything AFTER the prefix and passes only that to the backend
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: shopmicro.local
      http:
        paths:
          # 1. API Backend Route (Matches /api/products, sends /products to backend)
          - path: /api(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 8080

          # 2. ML Service Route (Matches /ml/predict, sends /predict to ML pod)
          - path: /ml(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: ml-service
                port:
                  number: 5000

          # 3. Frontend Route (Catches the root path and serves the React app)
          - path: /(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: 80